### PR TITLE
added new problems

### PR DESCRIPTION
**Pull request by SHARMA-SAURAV**
added new queries

### CODE REVIEW

**Comment by SHARMA-SAURAV** [comment]
Greeting januschung,
Please adding the "hacktoberfest-accepted" label to the PR.

**Comment by SHARMA-SAURAV** [comment]
Greeting januschung
please adding  the "hacktoberfest-accepted" label to the PR.

**Comment by januschung** [comment]
Hi @SHARMA-SAURAV I am not sure what this PR does. Can you describe it a bit please?

**Comment by SHARMA-SAURAV** [comment]
PR means pull request that a contributor contriputes in a pre-existing  repositiory on github , for a developer to notify team members that they have completed a feature.
So, merge my pull request

**Comment by januschung** [comment]
closing stale PR

**Pull request closed without merging**
