### PR TITLE
workflow to run pylint

### PR DESCRIPTION
**Pull request by riderius**

### CODE REVIEW

**Review by januschung — CHANGES_REQUESTED** [review]
how about add it to python-app.yml? Never tried pylint but why not.

Please name the step as Lint with pylint after the block for flake8

**Comment by RIDERIUS** [comment]
@januschung, done

**Comment by januschung** [comment]
@RIDERIUS the check is a little bit too harsh...I might have to reconsider it

**Comment by RIDERIUS** [comment]
Hi @januschung ! I fixed the pylint errors in run.py. But I don’t know how to fix the pylint error in the “test_math_worksheet_generator.py” file that occurs when using this command: “pylint` ls -R | grep .py $ | xargs` ". So, pylint now only checks out run.py, not the whole repository.

**Comment by RIDERIUS** [comment]
Hi @januschung. I have corrected the command in pylint parsing. Pylint now checks all `*.py` files in the repository. This allows the command: `find -name" * .py "-exec pylint {} \;`. Please correct the conflicts in the run.py file.

**Comment by januschung** [comment]
Thanks but I choose not to implement it.

**Pull request closed without merging**
